"""create username column

Revision ID: 2400b5c601a5
Revises: 80368e171d1f
Create Date: 2026-05-07 19:59:06.761862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2400b5c601a5'
down_revision = '80368e171d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
